version: "3.9"
services:
  webui:
    build:
      context: .
      dockerfile: stable_diffusion_webui.dockerfile
    ports:
      - "3000:7860"
    volumes:
      - ./models:/srv/webui/models/  
      - ./repositories:/srv/webui/repositories/ 
      - ./extensions:/srv/webui/extensions/
      - ./outputs:/srv/webui/outputs/
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    security_opt:
      - seccomp:unconfined
    group_add:
      - keep-groups
