version: "3.9"
services:
  webui:
    build:
      context: .
      dockerfile: stable_diffusion_automatic1111.dockerfile
    ports:
      - "3000:7860"
    volumes:
      - ./webui/models:/srv/webui/models/  
      - ./webui/repositories:/srv/webui/repositories/ 
      - ./webui/extensions:/srv/webui/extensions/
      - ./webui/outputs:/srv/webui/outputs/
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    security_opt:
      - seccomp:unconfined
    group_add:
      - keep-groups
